# Generated by Django 4.1.5 on 2023-02-08 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('gramme', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Składniki',
                'verbose_name_plural': 'Składniki',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ingredient', models.ManyToManyField(to='YourCalc.ingredient')),
            ],
            options={
                'verbose_name': 'Posiłek',
                'verbose_name_plural': 'Posiłek',
            },
        ),
        migrations.CreateModel(
            name='TimeofDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Śniadanie', 'Śniadanie'), ('Obiad', 'Obiad'), ('Kolacja', 'Kolacja')], max_length=64)),
            ],
            options={
                'verbose_name': 'Pora jedzenia',
                'verbose_name_plural': 'Pora jedzenia',
            },
        ),
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=64)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YourCalc.meal')),
                ('timeofday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YourCalc.timeofday')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dzień tygodnia',
                'verbose_name_plural': 'Dni tygodnia',
            },
        ),
    ]
